<style>
    span.changelink
    {
        display: none;
    }
</style>
<h3><?php echo $this->__( 'You will be redirected to your bank for secure payment. Wait a moment, please ...' ) ?></h3><br /><br />
<div>
<iframe title="titulo" src="<?php echo $iframeUrl; ?>" width="800" height="350" frameborder="0"   marginheight="0" marginwidth="0" scrolling="no" style="border: 0px solid #000000;padding: 0px; margin: 0px">
</iframe>
</div>

