<?php
$standard = Mage::getSingleton('paytpvcom/standard');


$iframe_src = $standard->getPayTpvBankStoreUrl().'?'.$standard->getStandardAddUserFields();
?>
<fieldset class="form-list">
	<?php $_code=$this->getMethodCode() ?>
</fieldset>


<ul id="payment_form_<?php echo $_code ?>" class="form-list" style="display:none;">
    <?php 
    $saveCard = 0;
    $card_select = (isset($_POST["payment"]["card"]))?$_POST["payment"]["card"]:"";

    if (sizeof($this->getCustomerCards())>0 && !$isRecurring):?>
    
    <li id="saved_cards">
        <label for="card"><?php print $this->__('Pay by Credit Card');?>:</label>
        <div class="input-box">
        <select name="payment[card]" id="card" onChange="checkCardWS(this)">
              <?php 
              
              $selected = "selected=\"selected\"";
              foreach ($this->getCustomerCards() as $card){
                 $saveCard = 1;
                 $card_desc = ($card["card_desc"]!="")?"- " . $card["card_desc"]:"";
                 print "<option value=".$card['paytpv_iduser']." $selected>".$card["paytpv_cc"] . " (".$card["paytpv_brand"].") ". $card_desc . "</option>";
                 $selected = "";
              }
              ?>
              <option value='0'><?php print $this->__('NEW CARD');?></option>
        </select>
        </div>
        <?php if ($commerce_password==1){?>
            <div id="user_validation" style="<?php if ($saveCard==0 || $card_select==="0") print "display:none;";?>">
                <label for="userpwd"><?php echo $this->__('For security, enter your user password Store') . ":"?></label>  
                <div class="input-box">
                <input type="password" style="width:200px" name="payment[userpwd]" id="userpwd">
                </div>
            </div>
        <?php } ?>
    
    </li>

    <?php endif;?>
        
	<?php 
        $message = $this->getMessage();
        if($message != ''){
			echo "<p>".$message."</p>";
        }
    ?>

    <?php 

    $paytpviframe = $standard->getConfigData('paytpviframe');

    // Begin IF paytpviframe=0
    if ($paytpviframe!="1"){ 
    
    ?>

    <li id="payment_form_<?php echo $_code ?>_cc" <?php if($saveCard > 0 && $card_select!=="0"){?>style="display:none;"<?php } ?>>
        <ul>
            <?php if ($show_nameoncard):?>
            <li>
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" />
                </div>
            </li>
            <?php endif; ?>
            <?php if ($show_cctypes):?>
            <li>
                <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
                <div class="input-box">
                    <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </li>
            <?php endif; ?>
            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number<?php if ($show_cctypes) print " validate-cc-type";?>" value="" />
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <?php echo $this->getChildHtml() ?>
            <?php if($this->hasVerification()): ?>
            <li>
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                    </div>
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                </div>
            </li>
            <?php endif; ?>
            <?php if ($this->hasSsCardType()): ?>
            <li id="<?php echo $_code ?>_cc_type_ss_div">
                <ul class="inner-form">
                    <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
                    <li>
                        <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                        <span class="input-box">
                            <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                        </span>
                    </li>

                    <li>
                        <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                        <div class="input-box">
                            <div class="v-fix">
                                <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                                </select>
                            </div>
                            <div class="v-fix">
                                <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                                <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </li>
                    <li class="adv-container">&nbsp;</li>
                </ul>
                <script type="text/javascript">
                //<![CDATA[
                var SSChecked<?php echo $_code ?> = function() {
                    var elm = $('<?php echo $_code ?>_cc_type');
                    if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                        $('<?php echo $_code ?>_cc_type_ss_div').show();
                    } else {
                        $('<?php echo $_code ?>_cc_type_ss_div').hide();
                    }
                };

                Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
                SSChecked<?php echo $_code ?>();
                //]]>
                </script>
            </li>
            <?php endif; ?>
            <?php if (!$isRecurring):?>
            <li>
                <div class="input-box">
                <div id="storingStep" class="alert alert-info"  <?php if ($saveCard==1) print "style='display:none'";?>>
                    <!--
                    <h4><?php print $this->__('STREAMLINE YOUR FUTURE PURCHASES!');?></h4>
                    <?php print $this->__('Link a card to your account to make all procedures easily and quickly.');?>
                    <br>
                    -->
                    <input type="checkbox" name="payment[remember]" id="savecard" class="input-checkbox" checked> <?php print $this->__('Yes, remember my card accepting ');?><a class="open_conditions" href="#conditions"><?php print $this->__('terms and conditions of service');?></a>.
                </div>
                </div>
            <li>
            <?php endif; ?>
            <?php if ($isRecurring):?>
                <div class="alert alert-info">
                    <?php print $this->__('By subscribing you agree to the ');?> <a href="#conditions" class="open_conditions" href="#"><?php print $this->__('terms and conditions of service');?></a>.
                </div>

            <?php endif; ?>
        </ul>
    <li>

    <?php
    // END IF paytpviframe=0
    }else{
        ?>
        <div id="storingStep" class="alert alert-info" <?php if ($saveCard==1) print "style='display:none'";?>>
            <input type="checkbox" name="payment[remember]" id="savecard" class="input-checkbox" checked> <?php print $this->__('Yes, remember my card accepting ');?><a class="open_conditions" href="#conditions"><?php print $this->__('terms and conditions of service');?></a>.
        </div>
    <?php
    }
    ?>

    <input type="hidden" name="base_url" id="base_url" value="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB,array('_secure'=>true));?>">

    <input type="hidden" name="conditions_url" id="conditions_url" value="<?php print $this->getUrl('paytpvcom/standard/conditions');?>">
</ul>
