<?php
$standard = Mage::getSingleton('paytpvcom/standard');
$cc = $standard->getCCFromQuote();
$iframe_src = $standard->getPayTpvBankStoreUrl().'?'.$standard->getStandardAddUserFields();
?>
<fieldset class="form-list">
	<?php $_code=$this->getMethodCode() ?>
</fieldset>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
	<table>
		<colgroup>
			<col width="25px">
			<col width="*">
		</colgroup>
		<tr>
			<td>&nbsp;</td>
			<td>
		<?php
			$message = $this->getMessage();
			if($message != ''){ ?>
				<p><?php echo $message; ?></p>
		<?php } ?>
		<?php
			$cc = $this->getPaytpvCc();
			if($cc != ''){ ?>
				<p><?php echo sprintf($this->__('You have already %s credit card stored in you account, press "continue" to use it or ...'),$cc); ?></p>
		<?php } ?>
				<p><?php echo $this->__('Please enter your credit card data in the form below. The payment information will be stored in PayTpv PCI-DSS certified company') ?></p>
				<iframe src="<?php echo $iframe_src;?>"	name="paytpv"
				style="height: 150px;width: 480px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; border-image: initial;" marginheight="0" marginwidth="0" scrolling="no"></iframe>
			</td>
		</tr>
	</table>
</div>
