
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

    <script>


    function CheckForm(){
        $("#clockwait").show();
        $jq.ajax({
                url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
                type: "POST",
                data: {
                    'action': 'addCardData',
                    'cc_number': $jq("#cc_number").val(),
                    'cc_exp_month': $jq("#expiration").val(),
                    'cc_exp_year': $jq("#cc_exp_year").val(),
                    'cc_cid': $jq("#cc_cid").val(),
                    'ajax': true
                },
                success: function(result)
                {
                    if (result["DS_ERROR_ID"]!=0){
                        
                        $("#resp_error").show();
                        $("#form_pago").hide();
                        $("#clockwait").hide();

                    }else{
                        $("#IdUser").val(result["DS_IDUSER"]);
                        $("#TokenUser").val(result["DS_TOKEN_USER"]);

                        if ("107_TEST"=="<?php print $TRANSACTION_TYPE;?>"){
                            window.parent.location.reload();
                            return;
                        }                        

                        // Pago Seguro
                        if ("<?php print $DSECURE;?>"=="1"){
                            
                            $("#formulario").submit();
                            
                        // Pago No Seguro
                        }else{
                            $("#formulario").off('submit');
                            // Throw notification Test
                            $.post( '<?php print $URL_NOT;?>', $( "#formulario" ).serialize(), function( data ) {
                                // Go to Url OK
                                window.parent.location='<?php print Mage::getUrl("checkout/onepage/success")?>';
                            });
                        }
                    }
                },
                dataType:"json"
            });
        
        return false;

    }


    </script>


<body style="width:450px;">
<form name="formulario" id="formulario" target="_parent" action="<?php print Mage::getUrl("paytpvcom/standard/bankstore3dstest");?>" method="post">
<div id="form_pago" style="background-color:#fff;width:400px !important;">
    <div>
        <span style="font-family: arial;font-size: 12px;color: #333;">Titular de la tarjeta:</span>
    </div>
    <div>
        <input type="text" style="border: 1px solid #ccc; border-radius: 4px; padding: 5px;color: #333; font-size: 12px; margin: 0px 6px 10px 0;" maxlength="50" id="nombre" name="nombre" value="" onClick="this.value='';" />
    </div>
    <div>
        <span style="font-family: arial;font-size: 12px;color: #333;">Número de tarjeta:</span>
    </div>
    <div>
        <input type="text" style="border: 1px solid #ccc; border-radius: 4px; padding: 5px;color: #333; font-size: 12px; margin: 0px 6px 10px 0;" maxlength="16" id="cc_number" name="cc_number" value="" onClick="this.value='';" />
    </div>
    <div>
        <span style="font-family: arial;font-size: 12px;color: #333;">Fecha de caducidad:</span>
    </div>

    <div>
        <div style="display:inline">
            <select id="expiration" name="expiration" style="border: 1px solid #ccc;border-radius: 4px;padding: 5px;color: #333;font-size: 12px;margin: 0px 6px 10px 0; ">
            <option value="1">01</option>
            <option value="2">02</option>
            <option value="3">03</option>
            <option value="4">04</option>
            <option value="5">05</option>
            <option value="6">06</option>
            <option value="7">07</option>
            <option value="8">08</option>
            <option value="9">09</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            </select>        
        </div>
        <div style="display:inline">
            <select name="cc_exp_year" id="cc_exp_year" style="border: 1px solid #ccc;border-radius: 4px;padding: 5px;color: #333;font-size: 12px;margin: 0px 6px 10px 0; ">
            <option value=2015>2015</option><option value=16>2016</option><option value=17>2017</option><option value=18>2018</option><option value=19>2019</option><option value=2020>2020</option><option value=21>2021</option><option value=22>2022</option><option value=23>2023</option>
            </select>        
        </div>
    </div>
  
    <div><span style="font-family: arial;font-size: 12px;color: #333;">Código CVC2:</span></div>
    <div style="width:14%;"><input type="text" style="width:90% !important;border: 1px solid #ccc; border-radius: 4px; padding: 5px;color: #333; font-size: 12px; margin: 0px 6px 10px 0;" maxlength="4" id="cc_cid" name="cc_cid" value="" onClick="this.value='';" /></div>
    
    <div style="width:14%;">
        <img src="<?php print $BASE_URL;?>/skin/frontend/base/default/images/paytpvcom/cvv2.png" alt="CVC2" width="34" height="21" title="CVC2" style="margin-left:5px; float:left;" />
    </div>
    <div style="width:70%;">
        <span style="font-family: arial;font-size: 12px;color: #333;">(Los 3 últimos dígitos)</span>
    </div>
    
    <br>
  
    <input type="button" onClick="CheckForm();" style="background-color: #0099e6;border: 1px solid #0099e6;color: #fff;font-weight: bold;border-radius: 3px;padding: 5px 10px;" value="Aceptar pago" class="boton" id="btnforg" />

    <div><img src="<?php print $BASE_URL;?>/skin/frontend/base/default/images/paytpvcom/clockpayblue.gif" alt="Espere" width="41" height="30" id="clockwait" style="display:none; margin-top:5px;" /></div>

    <input type="hidden" name="TransactionType" value="<?php print $TRANSACTION_TYPE;?>">
    <input type="hidden" name="Order" value="<?php print $MERCHANT_ORDER;?>">
    <input type="hidden" name="Amount" value="<?php print $MERCHANT_AMOUNT;?>">
    <input type="hidden" name="Response" value="OK">
    <input type="hidden" name="ExtendedSignature" value="<?php print $MERCHANT_MERCHANTSIGNATURE;?>">
    <input type="hidden" name="IdUser" id="IdUser" value="<?php print $ID_USER;?>">
    <input type="hidden" name="TokenUser" id="TokenUser"  value="<?php print $TOKEN_USER;?>">
    <input type="hidden" name="Currency" value="<?php print $MERCHANT_CURRENCY;?>">
    <input type="hidden" name="AuthCode" value="Test_mode">
    <input type="hidden" name="TestNoSecure" value="1">

</div>



<div id="resp_error" style="display:none;width:100%;" marginwidth="0" marginheight="0">
    <div style="margin-top:15px !important;background-color:#fff;width:400px !important;">
    <div style="float:left;width:98%;margin-top:13px;"><span style="font-family: arial;font-size: 12px;color: #333;">No se ha podido realizar correctamente la operación por el siguiente motivo:</span></div>
    <div style="float:left;width:98%;margin-top:13px;"><b><span style="font-family: arial;font-size: 12px;color: #333;">Error durante el proceso<br><span class="bigger">Error Inesperado. Verifique los datos de la tarjeta y pruebe de nuevo.</span></span></b></div>
    </div>
    <div style="margin-top:20px !important;background-color:#fff;width:400px !important;">
    <div style="float:left;width:30%;"><input type="button" value="Volver" style="background-color: #0099e6;border: 1px solid #0099e6;color: #fff;font-weight: bold;border-radius: 3px;padding: 5px 10px;" onclick="document.location=document.location"></div>
     <div style="float:left;width:30%;"><input type="button" value="Finalizar" style="background-color: #0099e6;border: 1px solid #0099e6;color: #fff;font-weight: bold;border-radius: 3px;padding: 5px 10px;" onclick="parent.location='{$URL_KO}'"></div>
</div>
</form>

