<h3><?php echo $this->__( 'Los datos de introducidos se almacenarán en los servidores de PayTpv, empresa con certificación PCI/DSS de nivel 1, lo que hace los pagos 100% seguros.' ) ?></h3><br /><br />
<iframe title="titulo"
		src="<?php echo $iframeUrl; ?>"
		width="800"
		height="350"
		frameborder="0"
		marginheight="0"
		marginwidth="0"
		scrolling="no"
		style="border: 0px solid #000000;padding: 0px; margin: 0px">
</iframe>