<h3><?php echo $this->__( 'The input data is stored on servers in PayTPV company with PCI / DSS Level 1 certification, making payments 100% secure.' ) ?></h3><br /><br />
<iframe title="titulo"
		src="<?php echo $iframeUrl; ?>"
		width="800"
		height="350"
		frameborder="0"
		marginheight="0"
		marginwidth="0"
		scrolling="no"
		style="border: 0px solid #000000;padding: 0px; margin: 0px">
</iframe>