<?php echo $this->getFormRedirect(); ?>
<center><br /><br />
<h3><?php echo $this->__('Al pinchar en continuar te derivaremos a la pasarela de pago de PayTPV , ning&uacute;n dato de la tarjeta se guarda en nuestros servidores, lo que hace los pagos 100% seguros.') ?></h3><br /><br />
<a href='<?php echo Mage::getUrl("paytpvcom/standard/visa/") ?>' target="_blank">
	<img src='<?php echo $this->getSkinUrl('images/paytpvcom/verifiedbyvisa.png') ?>' border="0" />
</a>&nbsp;&nbsp;
<a href='<?php echo Mage::getUrl("paytpvcom/standard/mastercard/")?>' target="_blank">
	<img src='<?php echo $this->getSkinUrl('images/paytpvcom/mastercard_secuercode.png') ?>' border="0" />
</a><br />
<input class="form-button" type="button" onclick="document.getElementById('paytpv_standard_checkout').submit();" value='<?php echo $this->__('Enviar') ?>' />
<script type="text/javascript">document.getElementById('paytpv_standard_checkout').submit();</script><br /><br /><br /><br />
</center>