<?php echo $this->getFormRedirect(); ?>
<center><br /><br />
<h3><?php echo $this->__('You will be redirected to your bank for secure payment. Wait a moment, please ..') ?></h3><br /><br />
<input class="form-button" type="button" onclick="document.getElementById('paytpv_standard_checkout').submit();" value='<?php echo $this->__('Enviar') ?>' />
<script type="text/javascript">document.getElementById('paytpv_standard_checkout').submit();</script>
</center>