<script type="text/javascript">
//<![CDATA[
    $jq(document).ready(function() {
        $jq("#open_conditions").fancybox({
                href: "<?php echo $this->getUrl('paytpvcom/standard/conditions') ?>",
                autoSize:false,
                type : 'ajax',
                'width':parseInt($jq(window).width() * 0.7)
            });
        
        $jq(".remove_card").on("click", function(e){   
            e.preventDefault();
            $jq("#customer_id").val($jq(this).attr("id"));
            cc = $jq("#card_"+$jq(this).attr("id")+"_cc").val();

            confirm("<?php print $this->__('Remove Card');?>" + ": " + cc, true, function(resp) {
                if (resp)   removeCard();
            });
        });

        $jq(".save_desc").on("click", function(e){   
            e.preventDefault();
            $jq("#customer_id").val($jq(this).attr("id"));
            cc = $jq("#card_desc_"+$jq(this).attr("id")).val();

            confirm("<?php print $this->__('Save Description');?>" + ": " + cc, true, function(resp) {
                if (resp)   saveDescriptionCard();
            });
        });
    });

    function confirm(msg, modal, callback) {
        $jq.fancybox("#confirm",{
            modal: modal,
            'width':400,
            'height': 'auto',
            'autoSize' : false,
            beforeShow: function() {
                $jq(".title").html(msg);
            },
            afterShow: function() {
                $jq(".confirm").on("click", function(event){
                    if($jq(event.target).is(".yes")){
                        ret = true;
                    } else if ($jq(event.target).is(".no")){
                        ret = false;
                    }
                    $jq.fancybox.close();
                });
            },
            afterClose: function() {
                callback.call(this, ret);
            }
        });
    }

    function alert(msg) {
        $jq.fancybox("#alert",{
            beforeShow: function() {
                $jq(".title").html(msg);
            },
            modal: false,
        });
    }

    function vincularTarjeta(){
        if ($jq("#savecard").is(':checked')){
            $jq('#savecard').attr("disabled", true);
            $jq('#close_vincular').show();
            $jq('#open_vincular').hide();
            $jq('#nueva_tarjeta').show();
        }else{
            alert("<?php print $this->__('You must accept the terms and conditions of service');?>");
        }

    }

    function close_vincularTarjeta(){
        $jq('#savecard').attr("disabled", false);
        $jq('#nueva_tarjeta').hide();
        $jq('#close_vincular').hide();
        $jq('#open_vincular').show();
    }

    

    function removeCard()
    {
        customer_id = $jq("#customer_id").val();

        $jq.ajax({
            url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
            type: "POST",
            data: {
                'action': 'removeCard',
                'customer_id': customer_id,
                'ajax': true
            },
            success: function(result)
            {
                if (result == '0')
                {
                   $jq("#card_"+customer_id).hide();
                }
            }
        });
        
    };

    function saveDescriptionCard()
    {
        customer_id = $jq("#customer_id").val();
        card_desc = $jq("#card_desc_"+customer_id).val();
        $jq.ajax({
            url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
            type: "POST",
            data: {
                'action': 'saveDescriptionCard',
                'customer_id': customer_id,
                'card_desc': card_desc,
                'ajax': true
            },
            success: function(result)
            {
                if (result == '0')
                {
                   alert("<?php print $this->__('Description saved');?>");
                }
            }
        });
        
    };


    function addCard(){
        if(customForm.validator && customForm.validator.validate()) {
            $jq.ajax({
                url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
                type: "POST",
                data: {
                    'action': 'addCard',
                    'cc_number': $jq("#cc_number").val(),
                    'cc_exp_month': $jq("#expiration").val(),
                    'cc_exp_year': $jq("#expiration_yr").val(),
                    'cc_cid': $jq("#cc_cid").val(),
                    'ajax': true
                },
                success: function(result)
                {
                    if (result == '')
                    {
                       window.location.reload();
                    }else{
                        alert(result)
                    }
                }
            });
        }
    };
//]]>
</script>


<div id="paytpv_block_account">
    <div class="page-title">
        <h1><?php print strtoupper($this->__('My Cards'));?></h1>
    </div>
    <?php if (sizeof($this->getCustomerCards())>0){?>
        <div class="span6" id="div_tarjetas">
            <?php print $this->__('Available Cards');?>:
            <?php foreach ($this->getCustomerCards() as $card){
                print "<div class='bankstoreCard' id='card_".$card["customer_id"]."'>";
                    print $card["paytpv_cc"] . " (". $card["paytpv_brand"] . ")";
                    print " <input type='text' maxlength='32' style='width:300px' id='card_desc_".$card["customer_id"]."' name='card_desc_".$card["customer_id"]."' value='".$card["card_desc"]."' placeholder='".$this->__('add description')."'>";
                    print "<label class='button_del'>";
                        print "<a href='#' id='".$card["customer_id"]."' class='save_desc'>";
                        print $this->__('Save Description');
                        print "</a>";
                        print " | ";
                        print "<a href='#' id='".$card["customer_id"]."' class='remove_card'>";
                        print $this->__('Remove Card');
                        print "</a>";
                       
                    print "</label>";
                   
                    print "<input type=\"hidden\" name=\"card_".$card["customer_id"]."_cc\" id=\"card_".$card["customer_id"]."_cc\" value=\"".$card["paytpv_cc"]."\">";
                print "</div>";
            }?>
        </div>
    <?php }else{?>
        <p class="warning"><?php print $this->__('There is still no card associated.');?></p>
    <?php }?>

    <div id="storingStep" class="alert alert-info" style="display: block;">
        <h4><?php print $this->__('STREAMLLINE YOUR FUTURE PURCHASES!');?></h4>
        <?php print $this->__('Link a card to your account to make all procedures easily and quickly.');?>
        <br>
        <input type="checkbox" name="savecard" id="savecard"> 
        <label for="savecard"><?php print $this->__('When you link a Tarjet accepts ');?> <a id="open_conditions" href="#conditions"><span class="terminos"><?php print $this->__('terms and conditions of service');?></span></a>.</label>
        <a href="javascript:void(0);" onclick="vincularTarjeta();" id="open_vincular" title="<?php print $this->__('Vincular Tarjeta de crédito');?>" class="button button-small btn btn-default">
            <?php print $this->__('Link card');?>
        </a>
        <a href="javascript:void(0);" onclick="close_vincularTarjeta();" title="<?php print $this->__('Cancelar');?>" class="button button-small btn btn-default" id="close_vincular" style="display:none">
                <?php print $this->__('Cancel');?>
        </a>
        <div class="payment_module paytpv_iframe" id="nueva_tarjeta" style="display:none">

            <form name="credit_card" id="credit_card" class="sp-methods">

            <ul class="form-list" id="payment_form_credit_card">
            <li>
                <label for="cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input maxlength="16" type="text" id="cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number required-entry" value=""/>
                </div>
            </li>
            <li>
                <label for="expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="expiration" name="payment[cc_exp_month]" class="month required-entry" autocomplete="off">
                            <option value="1">01</option>
                            <option value="2">02</option>
                            <option value="3">03</option>
                            <option value="4">04</option>
                            <option value="5">05</option>
                            <option value="6">06</option>
                            <option value="7">07</option>
                            <option value="8">08</option>
                            <option value="9">09</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select id="expiration_yr" name="payment[cc_exp_year]" class="year required-entry" autocomplete="off">
                            <?php $date = date("Y");
                            for($year=$date;$year<$date+11;$year++){
                                print "<option value=".$year.">".$year."</option>";
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </li>
            
            <li>
                <label for="cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input maxlength="4" size="4" type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="cc_cid" name="payment[cc_cid]" value="" />
                    </div>
                    <?php echo $this->__('CVC2') ?>
                </div>
            </li>
            <button type="button" class="button" onclick="addCard()"><span><span><?php echo $this->__('Aceptar') ?></span></span></button>
            <input type="hidden" name="base_url" id="base_url" value="<?php print Mage::getBaseUrl();?>">
            </form>

            <script type="text/javascript">
                //< ![CDATA[
                    var customForm = new VarienForm('credit_card');
                //]]>
            </script>

        </ul>

        </div>
    </div>
    <br/>
    
    <div id="alert" style="display:none">
        <p class="title"></p>
    </div>

    <div id="confirm" style="display:none">
        <p class="title"></p>
        <input type="button" class="confirm yes button" value="<?php print $this->__('Accept');?>" />
        <input type="button" class="confirm no button" value="<?php print $this->__('Cancel');?>" />
        <input type="hidden" name="customer_id" id="customer_id">
        <input type="hidden" name="suscription_id" id="suscription_id">
    </div>

    <div style="display: none;">
        <div id="conditions" style="overflow:auto;">
        </div>
    </div>
</div>
