<script type="text/javascript">
//<![CDATA[
    $jq(document).ready(function() {
        $jq("#open_conditions").fancybox({
                href: "<?php echo $this->getUrl('paytpvcom/standard/conditions') ?>",
                autoSize:false,
                type : 'ajax',
                'width':parseInt($jq(window).width() * 0.7)
            });
        
        $jq(".remove_card").on("click", function(e){   
            e.preventDefault();
            $jq("#customer_id").val($jq(this).attr("id"));
            cc = $jq("#card_"+$jq(this).attr("id")+"_cc").val();

            confirm("<?php print $this->__('Remove Card');?>" + ": " + cc, true, function(resp) {
                if (resp)   removeCard();
            });
        });

        $jq(".save_desc").on("click", function(e){   
            e.preventDefault();
            $jq("#customer_id").val($jq(this).attr("id"));
            cc = $jq("#card_desc_"+$jq(this).attr("id")).val();

            confirm("<?php print $this->__('Save Description');?>" + ": " + cc, true, function(resp) {
                if (resp)   saveDescriptionCard();
            });
        });
    });

    function confirm(msg, modal, callback) {
        $jq.fancybox("#confirm",{
            modal: modal,
            'width':400,
            'height': 'auto',
            'autoSize' : false,
            beforeShow: function() {
                $jq(".title").html(msg);
            },
            afterShow: function() {
                $jq(".confirm").on("click", function(event){
                    if($jq(event.target).is(".yes")){
                        ret = true;
                    } else if ($jq(event.target).is(".no")){
                        ret = false;
                    }
                    $jq.fancybox.close();
                });
            },
            afterClose: function() {
                callback.call(this, ret);
            }
        });
    }

    function alert(msg) {
        $jq.fancybox("#alert",{
            beforeShow: function() {
                $jq(".title").html(msg);
            },
            modal: false,
        });
    }

    function vincularTarjeta(){
        if ($jq("#savecard").is(':checked')){
            // if Bankstore Iframe/XML and Fullscreen
            <?php if ($integration==0 && $paytpviframe==1 && $paytpvfullscreen==1){ ?>
                window.open("<?php echo $iframeUrl;?>","_self");
                return;
            <?php
            }
            ?>

            $jq('#savecard').attr("disabled", true);
            $jq('#close_vincular').show();
            $jq('#open_vincular').hide();
            $jq('#nueva_tarjeta').show();

        }else{
            alert("<?php print $this->__('You must accept the terms and conditions of service');?>");
        }

    }

    function close_vincularTarjeta(){
        $jq('#savecard').attr("disabled", false);
        $jq('#nueva_tarjeta').hide();
        $jq('#close_vincular').hide();
        $jq('#open_vincular').show();
    }

    

    function removeCard()
    {
        customer_id = $jq("#customer_id").val();

        $jq.ajax({
            url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
            type: "POST",
            data: {
                'action': 'removeCard',
                'customer_id': customer_id,
                'ajax': true
            },
            success: function(result)
            {
                if (result == '0')
                {
                   $jq("#card_"+customer_id).hide();
                }
            }
        });
        
    };

    function saveDescriptionCard()
    {
        customer_id = $jq("#customer_id").val();
        card_desc = $jq("#card_desc_"+customer_id).val();
        $jq.ajax({
            url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
            type: "POST",
            data: {
                'action': 'saveDescriptionCard',
                'customer_id': customer_id,
                'card_desc': card_desc,
                'ajax': true
            },
            success: function(result)
            {
                if (result == '0')
                {
                   alert("<?php print $this->__('Description saved');?>");
                }
            }
        });
        
    };


    function addCard(){
        if(customForm.validator && customForm.validator.validate()) {
            $jq.ajax({
                url: "<?php echo $this->getUrl('paytpvcom/standard/actions') ?>",
                type: "POST",
                data: {
                    'action': 'addCard',
                    'cc_number': $jq("#cc_number").val(),
                    'cc_exp_month': $jq("#expiration").val(),
                    'cc_exp_year': $jq("#expiration_yr").val(),
                    'cc_cid': $jq("#cc_cid").val(),
                    'ajax': true
                },
                success: function(result)
                {
                    if (result == '')
                    {
                       window.location.reload();
                    }else{
                        alert(result)
                    }
                }
            });
        }
    };
//]]>
</script>


<div id="paytpv_block_account">
    <div class="page-title">
        <h1><?php print strtoupper($this->__('My Cards'));?></h1>
    </div>
    <?php if (sizeof($this->getCustomerCards())>0){?>
        <div class="span6" id="div_tarjetas">
            <?php print $this->__('Available Cards');?>:
            <?php foreach ($this->getCustomerCards() as $card){
                print "<div class='bankstoreCard' id='card_".$card["customer_id"]."'>";
                    print $card["paytpv_cc"] . " (". $card["paytpv_brand"] . ")";
                    print " <input type='text' maxlength='32' style='width:300px' id='card_desc_".$card["customer_id"]."' name='card_desc_".$card["customer_id"]."' value='".$card["card_desc"]."' placeholder='".$this->__('add description')."'>";
                    print "<label class='button_del'>";
                        print "<a href='#' id='".$card["customer_id"]."' class='save_desc'>";
                        print $this->__('Save Description');
                        print "</a>";
                        print " | ";
                        print "<a href='#' id='".$card["customer_id"]."' class='remove_card'>";
                        print $this->__('Remove Card');
                        print "</a>";
                       
                    print "</label>";
                   
                    print "<input type=\"hidden\" name=\"card_".$card["customer_id"]."_cc\" id=\"card_".$card["customer_id"]."_cc\" value=\"".$card["paytpv_cc"]."\">";
                print "</div>";
            }?>
        </div>
    <?php }else{?>
        <p class="warning"><?php print $this->__('There is still no card associated.');?></p>
    <?php }?>

    <div id="storingStep" class="alert alert-info" style="display: block;">
        <h4><?php print $this->__('STREAMLINE YOUR FUTURE PURCHASES!');?></h4>
        <?php print $this->__('Link a card to your account to make all procedures easily and quickly.');?>
        <br>
        <input type="checkbox" name="savecard" id="savecard"> 
        <label for="savecard"><?php print $this->__('When you link a Tarjet accepts ');?> <a id="open_conditions" href="#conditions"><span class="terminos"><?php print $this->__('terms and conditions of service');?></span></a>.</label>
        <a href="javascript:void(0);" onclick="vincularTarjeta();" id="open_vincular" title="<?php print $this->__('Vincular Tarjeta de crédito');?>" class="button button-small btn btn-default">
            <?php print $this->__('Link card');?>
        </a>
        <a href="javascript:void(0);" onclick="close_vincularTarjeta();" title="<?php print $this->__('Cancelar');?>" class="button button-small btn btn-default" id="close_vincular" style="display:none">
                <?php print $this->__('Cancel');?>
        </a>
        <div class="payment_module paytpv_iframe" id="nueva_tarjeta" style="display:none">

            <?php if ($integration==1){?>

                <div class="paytpv_jet user">

                <form name="paytpvPaymentForm" id="paytpvPaymentForm" method="POST" action="<?php print $this->getUrl("paytpvcom/standard/bkjetadduser");?>" onsubmit="return addCardJet();">
   
                <h4><?php echo $this->__('Enter your card'); ?></h4>
                <ul>
                    <li>
                        <label for="MERCHANT_PAN"><?php echo $this->__('Credit Card Number') ?>:</label>
                        <input type="text" data-paytpv="paNumber" width="360" maxlength="16" value="" required="required" placeholder="1234 5678 9012 3456" pattern="[0-9]{15,16}" onclick="this.value='';">
                    </li>
                    <li class="vertical">
                        <ul>
                            <li>
                                <label for="expiry_date"><?php echo $this->__('Expiration') ?></label>
                                <input maxlength="5" placeholder="<?php echo $this->__('mm/yy') ?>" id="expiry_date" required="required" pattern="[0-9]{2}/+[0-9]{2}" type="text" onChange="buildED();">
                                <input type="hidden" data-paytpv="dateMonth" maxlength="2"  value="">
                                <input type="hidden" data-paytpv="dateYear" maxlength="2" value="">
                            </li>
                            <li>
                                <label for="MERCHANT_CVC2"><?php echo $this->__('CVV') ?></label>
                                <input type="text" data-paytpv="cvc2" maxlength="4" value="" required="required" placeholder="123" pattern="[0-9]{3,4}" onclick="this.value='';">
                    
                            </li>
                            <small class="help"><?php echo $this->__('The CVV is a numerical code, usually 3 digits behind the card') ?>.</small>
                        </ul>
                    </li>
                    
                    <li>
                        <label for="Nombre"><?php echo $this->__('Name on Card') ?>:</label>
                        <input type="text" class="paytpv_cardholdername" data-paytpv="cardHolderName" width="360" maxlength="50" value="" required="required" placeholder="<?php echo $this->__('Name on Card') ?>" onclick="this.value='';">
                    </li>

                    <li>
                        <input type="submit" class="button" value="<?php echo $this->__('Link card') ?>" id="btnforg" style="" onclick="buildED();">
                      <div class="button" id="clockwait" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/paytpvcom/loader.gif') ?>" title="<?php echo $this->__('Wait');?>" /></div>
                      </li>

                    <span style="color:red;font-weight:bold;" id="paymentErrorMsg"></span>
                    <input type="hidden" name="payment[paytpvToken]" id="paytpvToken">
                </ul>
                </form>

                </div>
              
          
                <script type="text/javascript">
                //<![CDATA[
                <?php 
                include("paytpv/Minifier.php");

                $js_code = "
                    (function() {
                        (function() {
                            var $,
                            __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

                            $ = " . '$jq' . ";

                " . '$jq' . ".fn.validateCreditCard = function(callback, options) {
                    var bind, card, card_type, card_types, get_card_type, is_valid_length, is_valid_luhn, normalize, validate, validate_number, _i, _len, _ref;
                    card_types = [
                  {
                    name: 'amex',
                    pattern: /^3[47]/,
                    valid_length: [15]
                  }, {
                    name: 'diners_club_carte_blanche',
                    pattern: /^30[0-5]/,
                    valid_length: [14]
                  }, {
                    name: 'diners_club_international',
                    pattern: /^36/,
                    valid_length: [14]
                  }, {
                    name: 'jcb',
                    pattern: /^35(2[89]|[3-8][0-9])/,
                    valid_length: [16]
                  }, {
                    name: 'laser',
                    pattern: /^(6304|670[69]|6771)/,
                    valid_length: [16, 17, 18, 19]
                  }, {
                    name: 'visa_electron',
                    pattern: /^(4026|417500|4508|4844|491(3|7))/,
                    valid_length: [16]
                  }, {
                    name: 'visa',
                    pattern: /^4/,
                    valid_length: [16]
                  }, {
                    name: 'mastercard',
                    // 20160603 2U7-GQS-M6X3 Cambiamos el patern ya que MC ha incluido nuevos rangos de bines
                    pattern: /^(5[1-5]|222|2[3-6]|27[0-1]|2720)/,
                    // 20160603 2U7-GQS-M6X3 Fin
                    valid_length: [16]
                  }, {
                    name: 'maestro',
                    pattern: /^(5018|5020|5038|6304|6759|676[1-3])/,
                    valid_length: [12, 13, 14, 15, 16, 17, 18, 19]
                  }, {
                    name: 'discover',
                    pattern: /^(6011|622(12[6-9]|1[3-9][0-9]|[2-8][0-9]{2}|9[0-1][0-9]|92[0-5]|64[4-9])|65)/,
                    valid_length: [16]
                  }
                ];
                bind = false;
                if (callback) {
                  if (typeof callback === 'object') {
                    options = callback;
                    bind = false;
                    callback = null;
                  } else if (typeof callback === 'function') {
                    bind = true;
                  }
                }
                if (options === null) {
                  options = {};
                }
                if (options.accept === null) {
                  options.accept = (function() {
                    var _i, _len, _results;
                    _results = [];
                    for (_i = 0, _len = card_types.length; _i < _len; _i++) {
                      card = card_types[_i];
                      _results.push(card.name);
                    }
                    return _results;
                  })();
                }
                _ref = options.accept;
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  card_type = _ref[_i];
                  if (__indexOf.call((function() {
                    var _j, _len1, _results;
                    _results = [];
                    for (_j = 0, _len1 = card_types.length; _j < _len1; _j++) {
                      card = card_types[_j];
                      _results.push(card.name);
                    }
                    return _results;
                  })(), card_type) < 0) {
                    throw 'Tarjeta no válida';
                  }
                }
                get_card_type = function(number) {
                  var _j, _len1, _ref1;
                  _ref1 = (function() {
                    var _k, _len1, _ref1, _results;
                    _results = [];
                    for (_k = 0, _len1 = card_types.length; _k < _len1; _k++) {
                      card = card_types[_k];
                      if (_ref1 = card.name, __indexOf.call(options.accept, _ref1) >= 0) {
                        _results.push(card);
                      }
                    }
                    return _results;
                  })();
                  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                    card_type = _ref1[_j];
                    if (number.match(card_type.pattern)) {
                      return card_type;
                    }
                  }
                  return null;
                };
                is_valid_luhn = function(number) {
                  var digit, n, sum, _j, _len1, _ref1;
                  sum = 0;
                  _ref1 = number.split('').reverse();
                  for (n = _j = 0, _len1 = _ref1.length; _j < _len1; n = ++_j) {
                    digit = _ref1[n];
                    digit = +digit;
                    if (n % 2) {
                      digit *= 2;
                      if (digit < 10) {
                        sum += digit;
                      } else {
                        sum += digit - 9;
                      }
                    } else {
                      sum += digit;
                    }
                  }
                  return sum % 10 === 0;
                };
                is_valid_length = function(number, card_type) {
                  var _ref1;
                  return _ref1 = number.length, __indexOf.call(card_type.valid_length, _ref1) >= 0;
                };
                validate_number = (function(_this) {
                  return function(number) {
                    var length_valid, luhn_valid;
                    card_type = get_card_type(number);
                    luhn_valid = false;
                    length_valid = false;
                    if (card_type !== null) {
                      luhn_valid = is_valid_luhn(number);
                      length_valid = is_valid_length(number, card_type);
                    }
                    return {
                      card_type: card_type,
                      valid: luhn_valid && length_valid,
                      luhn_valid: luhn_valid,
                      length_valid: length_valid
                    };
                  };
                })(this);
                validate = (function(_this) {
                  return function() {
                    var number;
                    
                    number = normalize(_this.val());
                    return validate_number(number);
                  };
                })(this);
                normalize = function(number) {
                  return number.replace(/[ -]/g, '');
                };
                if (!bind) {
                  return validate();
                }
                this.on('input.jccv', (function(_this) {
                  return function() {
                    " . '$jq' . "(_this).off('keyup.jccv');
                    return callback.call(_this, validate());
                  };
                })(this));
                this.on('keyup.jccv', (function(_this) {
                  return function() {
                    return callback.call(_this, validate());
                  };
                })(this));
                  callback.call(this, validate());
                  return this;
                };

                }).call(this);
                    " . '$jq' . "(function() {
                        return " . '$jq' . "('[data-paytpv=\'paNumber\']').validateCreditCard(function(result) {
                        " . '$jq' . "(this).removeClass().addClass('paytpv_merchant_pan');
                            if (result.card_type === null) {
                                return;
                            }
                            " . '$jq' . "(this).addClass(result.card_type.name);
                            if (result.valid) {
                                return " . '$jq' . "(this).addClass('valid');
                            } else {
                                return " . '$jq' . "(this).removeClass('valid');
                            }
                        }, {
                        accept: ['visa', 'visa_electron', 'mastercard', 'maestro', 'discover', 'amex']
                        });
                    });
                }).call(this);

                buildED = function() {
                    var strED = document.getElementById('expiry_date').value;

                    var mm = strED.substr(0, 2);
                    var yy = strED.substr(3, 2);
                    " . '$jq' . "('[data-paytpv=\'dateMonth\']').val(mm), " . '$jq' . "('[data-paytpv=\'dateYear\']').val(yy)
                    return;
                }


                function getParameterByName(name, url) {
                    if (!url) url = document.location.href;
                    url = url.toLowerCase();
                    name = name.replace(/[\[\]]/g, '\\$&').toLowerCase();
                    var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
                    results = regex.exec(url);
                    if (!results) return null;
                    if (!results[2]) return '';
                    return decodeURIComponent(results[2].replace(/\+/g, ' '));
                }

                " . '$jq' . "(document).ready(function($) {

                    //createJetForm(0); // Create Jet Form
                    jQuery.getScript('https://secure.paytpv.com/gateway/jet_paytpv_js.php?id=" . $this->model->getConfigData('jetid') . "&language=" . $this->model->calcLanguage(Mage::app()->getLocale()->getLocaleCode()) ."');

                    " . '$jq' . "('#expiry_date').on('input',function(){
                        var curLength = " . '$jq' . "(this).val().length;
                        if(curLength === 2){
                            var newInput = " . '$jq' . "(this).val();
                            newInput += '/';
                            " . '$jq' . "(this).val(newInput);
                        }
                    });
               
                });

                function Verify(name, len) {
                  try {
                    var obj = " . '$jq' . "('[data-paytpv=\''+name+'\']');
                    
                    if(obj.val() == '' || obj.val() == 'Incompleto')
                    {
                      obj.css('border','1px solid #d99785');
                      obj.val('Incompleto');
                      return 0;
                    }

                    if(obj.val().length < len)
                    {
                      obj.css('border','1px solid #d99785');
                      obj.onclick = '';
                      return 0;
                    }

                    obj.css('border','1px solid #e0e0e0');
                    return 1;
                  }catch(err) {
                    
                    alert ('No es posible verificar la información');
                    return false;
                  }
                }

                function checkForm(){
                  if (Verify('cardHolderName') + Verify('paNumber', 14) + Verify('cvc2', 3) != 3)
                      return false;
                
                    if (checkCard( " . '$jq' . "('[data-paytpv=\'paNumber\']').val()) == false) {
                      " . '$jq' . "('[data-paytpv=\'paNumber\']').css('border','1px solid #d99785');
                      
                      return false;
                    }
                    
                    if (" . '$jq' . "('expiry_date').val()) { // Existe en el dom, con lo cual es un template fs. Hay que validarlo.
                      var objED = $('expiry_date');
                      var objVal = objED.val();
                      var mmPart = objVal.substr(0,2);
                      var yyPart = objVal.substr(3,2);
                      var dateNow = new Date();
                      var yearNow = dateNow.getFullYear().toString();
                      var yearNow2 = yearNow.substr(2,2);

                      if (parseInt(mmPart) < 0 || parseInt(mmPart) > 12) {
                        objED.css('border','1px solid #d99785');
                        return false;
                      }

                      if (parseInt(yyPart) < parseInt(yearNow2) || parseInt(yyPart) > parseInt(yearNow2)+10) {
                        objED.css('border','1px solid #d99785');
                        return false;
                      }
                    }
                    return true;
                }


                function checkCard(".'$card'."){
                   var c = ".'$card'.";
                   var cl = parseInt(c.substr(c.length - 1));
                   var c = c.slice(0,-1)
                   var c = c.split('').reverse().join('');
                   var c = c.split('');
                   var a = 2;
                   var cm = [];
                   for (var i = 0; i < c.length; i++){
                   if (a%2 == 0){var t = c[i]*2;
                   if (t > 9){var t = (t -9);}
                       cm.push(t);
                   } else {cm.push(parseInt(c[i]));}
                       a++;
                   }
                   var f = 0;
                   for (var i = 0; i < cm.length; i++) {f += cm[i];}
                   f = f + cl;
                   if (f%10 == 0) {
                       return true;
                  } else {
                      return false;
                  }
                }

                
                function addCardJet(){
                    resp = checkForm();
                    if (!resp)  return;
                    
                    buildED(); // set Jet Form Values
                    takingOff();
                    if (boarding_error==0){
                      ShowHidePaymentButton(false);
                      " . '$jq' . ".post( " . '$jq' . "('#paytpvPaymentForm').attr('action'), " . '$jq' . "('#paytpvPaymentForm').serialize(), function( data ) {
                          if (data.error==0){
                            window.location.reload();
                            ShowHidePaymentButton(true);
                          }else{
                            ShowHidePaymentButton(true);
                            " . '$jq' . "('.paymentError').show();
                            document.getElementById('paymentErrorMsg').innerHTML = data.errorText;
                          }
                      },'json');
                    }
                }

                function ShowHidePaymentButton(show){
                  
                  if (show){
                    " . '$jq' . "('#clockwait').hide('fast');
                    " . '$jq' . "('#btnforg').show('fast');
                  }else{
                    " . '$jq' . "('#btnforg').hide('fast');
                    " . '$jq' . "('#clockwait').show('fast');
                  }
                }

                function takingOff() {
                    var x = new PAYTPV.Tokenizator();
                    x.getToken(document.forms['paytpvPaymentForm'], boarding);
                    return false;
                };

                function boarding(passenger) {
                    boarding_error = 0;
                    document.getElementById('paymentErrorMsg').innerHTML = '';
                    if (passenger.errorID !== 0 || passenger.paytpvToken === '') {
                        " . '$jq' . "('.paymentError').show();
                        document.getElementById('paymentErrorMsg').innerHTML = passenger.errorText;
                        boarding_error = 1;
                    } else {
                        
                        var newInputField = document.createElement('input');

                        newInputField.type = 'hidden';
                        newInputField.name = 'paytpvToken';
                        newInputField.value = passenger.paytpvToken;

                        var paytpvPaymentForm = document.forms['paytpvPaymentForm'];
                        paytpvPaymentForm.appendChild(newInputField);

                        "  . '$jq' . "('#paytpvToken').val(passenger.paytpvToken);
                    }
                }

                ";
                print Minifier::minify($js_code);
              ?>
              //]]>
              </script>



            <?php } else if ($paytpviframe==1 && $paytpvfullscreen==0){?>
                <iframe src="<?php echo $iframeUrl;?>" name="paytpv" style="width: 670px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; border-image: initial; height: 450px; " marginheight="0" marginwidth="0" scrolling="no" sandbox="allow-top-navigation allow-scripts allow-same-origin allow-forms"></iframe>
            <?php } else if ($paytpviframe==0){ ?>
            
                <form name="credit_card" id="credit_card" class="sp-methods">

                <ul class="form-list" id="payment_form_credit_card">
                    <li>
                        <label for="cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                        <div class="input-box">
                            <input maxlength="16" type="text" id="cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number required-entry" value=""/>
                        </div>
                    </li>
                    <li>
                        <label for="expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                        <div class="input-box">
                            <div class="v-fix">
                                <select id="expiration" name="payment[cc_exp_month]" class="month required-entry" autocomplete="off">
                                    <option value="1">01</option>
                                    <option value="2">02</option>
                                    <option value="3">03</option>
                                    <option value="4">04</option>
                                    <option value="5">05</option>
                                    <option value="6">06</option>
                                    <option value="7">07</option>
                                    <option value="8">08</option>
                                    <option value="9">09</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                            </div>
                            <div class="v-fix">
                                <select id="expiration_yr" name="payment[cc_exp_year]" class="year required-entry" autocomplete="off">
                                    <?php $date = date("Y");
                                    for($year=$date;$year<$date+11;$year++){
                                        print "<option value=".$year.">".$year."</option>";
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </li>
                    
                    <li>
                        <label for="cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                        <div class="input-box">
                            <div class="v-fix">
                                <input maxlength="4" size="4" type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="cc_cid" name="payment[cc_cid]" value="" />
                            </div>
                            <?php echo $this->__('CVC2') ?>
                        </div>
                    </li>
                    <button type="button" class="button" onclick="addCard()"><span><span><?php echo $this->__('Aceptar') ?></span></span></button>
                    <input type="hidden" name="base_url" id="base_url" value="<?php print Mage::getBaseUrl();?>">
                    </form>

                    <script type="text/javascript">
                        //< ![CDATA[
                            var customForm = new VarienForm('credit_card');
                        //]]>
                    </script>

                </ul>

            <?php } ?>

        </div>
    </div>
    <br/>
    
    <div id="alert" style="display:none">
        <p class="title"></p>
    </div>

    <div id="confirm" style="display:none">
        <p class="title"></p>
        <input type="button" class="confirm yes button" value="<?php print $this->__('Accept');?>" />
        <input type="button" class="confirm no button" value="<?php print $this->__('Cancel');?>" />
        <input type="hidden" name="customer_id" id="customer_id">
        <input type="hidden" name="suscription_id" id="suscription_id">
    </div>

    <div style="display: none;">
        <div id="conditions" style="overflow:auto;">
        </div>
    </div>
</div>
